FROM gcr.io/spinnaker-marketplace/gradle_cache
MAINTAINER engineering@goodrx.com
ENV GRADLE_USER_HOME /gradle_cache/.gradle
COPY . compiled_sources
WORKDIR compiled_sources
RUN ./gradlew --no-daemon orca-web:installDist -x test
